docs: rewrite the new useFetch way of using it and the Composition API without the module as dependency
storyblok/storyblok-nuxt-2 pull request #82
Opened 2022-11-30 11:13 UTC by Dawntraoz

2022-12-01 09:54 UTC, alexjoverm submitted a review, later dismissed

2022-12-01 09:54 UTC, alexjoverm commented on README.md
> +> You don't need to install [@nuxtjs/composition-api](https://composition-api.nuxtjs.org/) as it's not a dependency anymore.
```suggestion
> You don't need to install [@nuxtjs/composition-api](https://composition-api.nuxtjs.org/) if you're in the latest versions of Nuxt 2, as it comes with Vue 2.7 with Composition API support out of the box.
```

2022-12-01 09:54 UTC, alexjoverm commented on README.md
> +#### Composition API without `@nuxtjs/composition-api`
I would move this section above, as I'd consider it the primary option

2022-12-01 14:05 UTC, Dawntraoz commented
@alexjoverm updated ☑️

2022-12-07 10:13 UTC, Dawntraoz commented
Hi @manuelschroederdev, as Alex is on PTO, can you double-check the updates on the Readme? 🫂

2022-12-12 17:56 UTC, Dawntraoz commented
@alexjoverm I added the fix and the alias update in this PR. When calling `fetch()` inside the module, then the `resolve_relations` are resolved, otherwise didn't resolve them while using `script setup`.

2022-12-13 09:40 UTC, alexjoverm requested changes

2022-12-13 09:40 UTC, alexjoverm commented on README.md
> +The simplest way is by using the `useStoryblok` one-liner composable, which uses the [useFetch from @nuxtjs/composition-api](https://composition-api.nuxtjs.org/lifecycle/useFetch) under the hood:
I realize I would skip the useFetch explanation, as it might be confusing for the user

2022-12-15 16:51 UTC, alexjoverm approved these changes

2022-12-21 08:50 UTC, merged